version: "3"
services:
  server:
    build: .
    image: superminingbros/zenbot:gerald-v3
    ports:
      - "3013:3013"
    links:
      - mongodb
      - reducer
      - btc-usd
      - ltc-usd
    volumes:
      - ./bin:/app/bin
      # - eth-usd # Uncomment for `eth-usd` support (also uncomment container below)
      #- eth-btc # Uncomment for `eth-btc` support (also uncomment container below)
    command: ["bin/wait-for-it.sh", "mongodb:27017", "--timeout=30", "-s", "--", "bin/server.sh"]

  reducer:
    image: superminingbros/zenbot:gerald-v3
    links:
      - mongodb
    volumes:
      - ./bin:/app/bin
    command: ["bin/wait-for-it.sh", "mongodb:27017", "--timeout=30", "-s", "--", "bin/reducer.sh"]

  btc-usd:
    image: superminingbros/zenbot:gerald-v3
    links:
      - mongodb
    volumes:
      - ./bin:/app/bin
    command: ["bin/wait-for-it.sh", "mongodb:27017", "--timeout=30", "-s", "--", "bin/run-btc-usd.sh"]

  ltc-usd:
      image: superminingbros/zenbot:gerald-v3
      links:
        - mongodb
      volumes:
        - ./bin:/app/bin
      command: ["bin/wait-for-it.sh", "mongodb:27017", "--timeout=30", "-s", "--", "bin/run-ltc-usd.sh"]

  ### Uncomment for `eth-usd` support
  # eth-usd:
  #   build: .
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   links:
  #     - mongodb
  #   command: ./run-eth-usd.sh
  ### /Uncomment for `eth-usd` support

  ### Uncomment for `eth-btc` support
#  eth-btc:
#   image: superminingbros/zenbot:gerald-v3
#   links:
#     - mongodb
#   command: ./run-eth-btc.sh
  ### /Uncomment for `eth-btc` support

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    links:
      - mongodb-data
    volumes:
      - mongodb-data:/data/db
#    healthcheck:
#      test: echo 'db.stats().ok' | mongo localhost:27017/zenbrain --quiet
#      interval: 5s
#      timeout: 5s
#      retries: 12
    command: ["mongod", "--smallfiles"]

  mongodb-data:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    command: ["true"]

volumes:
  mongodb-data:
